language: c

before_install:
    - curl -SLs https://raw.githubusercontent.com/sconaway/travis-arduino/master/travis.sh | bash
install:
    - arduino-cli lib update-index
    - arduino-cli lib install "Adafruit NeoPixel"

script: make
