language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/sconaway/travis-arduino/master/travis.sh)
script: make
notifications:
  email:
    on_success: change
    on_failure: change
